version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0

    steps:
      - checkout

      # Install Maven dependencies
      - run:
          name: Install Dependencies
          command: mvn install -DskipTests=true -B -V

      # Run tests from SpaceTagTests class
      - run:
          name: Run SpaceTagTests
          command: mvn -Dtest=SpaceTagTests test

      # Collect test results for CircleCI Insights (optional)
      - store_test_results:
          path: target/surefire-reports

      # Collect test artifacts for CircleCI Artifacts (optional)
      - store_artifacts:
          path: target/allure-results

workflows:
  version: 2
  build:
    jobs:
      - build
